PREFIX cx: <https://raw.githubusercontent.com/catenax-ng/product-knowledge/main/ontology/cx_ontology.ttl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?eMat ?engineeringMaterialName ?engineeringMaterialClass ?rMat ?componentState ?componentMaterialClass ?componentRecycledContent ?componentMaterialAbbreviation
WHERE {

    ?eMat cx:isMadeOf ?rMat;
        rdf:type cx:EngineeringMaterial;
        cx:engineeringMaterialName ?engineeringMaterialName;
        cx:engineeringMaterialNumber ?engineeringMaterialClass.
    ?rMat rdf:type cx:RawMaterial;
        cx:engineeringMaterialNumber ?componentMaterialClass;
        cx:hasMaterialProperty ?matProp;
        cx:engineeringMaterialName ?componentMaterialName.
    ?matProp #rdf:type cx:MaterialProperty;
        cx:aggregateState ?componentState;
        cx:recycledContent ?componentRecycledContent;
        cx:materialCode ?componentMaterialAbbreviation.
     }

ORDER BY DESC(?eMat)