PREFIX cx: <https://raw.githubusercontent.com/catenax-ng/product-knowledge/main/ontology/cx_ontology.ttl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?catenaXId ?validFrom ?validTo ?classification ?manufacturerPartId ?nameAtManufacturer
WHERE {
    ?catenaXId rdf:type cx:Part;
        cx:partSeries ?manufacturerPartId;
        cx:partName ?nameAtManufacturer;
        cx:partProductionDate ?validFrom;
        cx:partProductionDate ?validTo.
}
ORDER BY DESC(?catenaXId)