PREFIX cx: <https://raw.githubusercontent.com/catenax-ng/product-knowledge/main/ontology/cx_ontology.ttl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?catenaXId ?childCatenaXId ?childQuantity ?billOfMaterialUnit ?productionEndDate ?productionStartDate
WHERE {

    ?catenaXId rdf:type cx:Part;
        cx:hasBillOfMaterial ?bom.
    ?bom cx:billOfMaterialQuantity ?childQuantity;
        cx:hasItem ?childCatenaXId; # pretty sure that this is equivalent to cx:isPartOf
        cx:billOfMaterialUnit ?billOfMaterialUnit;
        cx:productionStartDate ?productionStartDate;
        cx:productionEndDate ?productionEndDate.
}
ORDER BY DESC(?catenaXId)